######################### General parameters ############################

# Simulations to be done

DMRSEQ_SIMULATION: True
WGBSSimla_SIMULATION: False

# Packages to tests in alphabetical order

BSSEQ: True
CGMAPTOOLS: False
DEFIANT: False
DMRCALLER: False
DMRSEQ: False
METHPIPE: False
METHYLKIT: False

CORES: 10

######################### Important paths ##############################

DATA: data/
SIM_DATA_DMRSEQ: exp/dmrseq_simulated_data/
SIM_DATA_WGBSSimla: exp/pWGBSSimla_simulated_data/
