---
title: "DMRcaller"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

According to https://bioconductor.org/packages/release/bioc/vignettes/DMRcaller/inst/doc/DMRcaller.pdf.

Setting directories:
```{r warning=FALSE, message=FALSE, eval=FALSE}
dataDir <- "data"
dir.create(file.path(dataDir))
resDir <- "results/dmrcaller"
dir.create(file.path(resDir))
ncores=2
```

#### Negative control
- prepare the data in required format:
```{r warning=FALSE, message=FALSE, eval=FALSE}
library("DMRcaller")

M <- read.table(paste(dataDir, "data_neg_control.M.gz", sep="/"), header=TRUE, sep="\t", stringsAsFactors = F)
cov <- read.table(paste(dataDir, "data_neg_control.cov.gz", sep="/"), header=TRUE, sep="\t", stringsAsFactors = F)
chr <- M$chr
pos <- M$pos
M$chr <- NULL
M$pos <- NULL
cov$chr <- NULL
cov$pos <- NULL

# required coverage: at least 5 in at least 2 samples in each group
keepLoci.ex <- which(rowSums(cov[, grp1] >= 5) >= 2 &
                     rowSums(cov[, grp2] >= 5) >= 2)
length(keepLoci.ex)
cov <- cov[keepLoci.ex,]
M <- M[keepLoci.ex,]
chr <- chr[keepLoci.ex]
pos <- pos[keepLoci.ex]

context <- rep('CG', length(chr)) #all data are from CpGs
tricontext <- rep('HCG', length(chr)) #trinucleotide context (won't be used, but is required)
strand <- rep('+', length(chr))

for(i in 1:6){
  meth.i <- M[,i]
  cov.i <- cov[,i]
  nmeth.i <- cov.i-meth.i
  new.data <- data.frame(chr=chr,
                       pos=pos,
                       strand=strand,
                       meth=meth.i,
                       nmeth=nmeth.i,
                       context=context,
                       tricontext=tricontext)
  filename <- paste(dataDir,"/data_neg_control_dmrcaller_", i, ".CX_report", sep="")
  write.table(new.data, file=filename, sep="\t", quote=FALSE, col.names=FALSE, row.names=FALSE)
}
```

- read in data
```{r warning=FALSE, message=FALSE, eval=FALSE}
mData1 <- readBismark(paste(dataDir,"/data_neg_control_dmrcaller_1.CX_report", sep=""))
mData2 <- readBismark(paste(dataDir,"/data_neg_control_dmrcaller_2.CX_report", sep=""))
mData3 <- readBismark(paste(dataDir,"/data_neg_control_dmrcaller_3.CX_report", sep=""))
mData4 <- readBismark(paste(dataDir,"/data_neg_control_dmrcaller_4.CX_report", sep=""))
mData5 <- readBismark(paste(dataDir,"/data_neg_control_dmrcaller_5.CX_report", sep=""))
mData6 <- readBismark(paste(dataDir,"/data_neg_control_dmrcaller_6.CX_report", sep=""))

methylationDataList <- GRangesList("rep1" = mData1,
              "rep2" = mData2,
              "rep3" = mData3,
              "rep4" = mData4,
              "rep5" = mData5,
              "rep6" = mData6)

grp1 <- c(1,3,5)
grp2 <- c(2,4,6)

mDataGrp1 <- poolMethylationDatasets(methylationDataList[grp1])
mDataGrp2 <- poolMethylationDatasets(methylationDataList[grp2])
```

- DMRs calling
  - `noise_filter` method with `triangular` kernel, Fisher test
```{r warning=FALSE, message=FALSE, eval=FALSE}
DMRsNoiseFilterTriangular <- computeDMRs(mDataGrp1, mDataGrp2,
  method = "noise_filter",
  kernelFunction = "triangular",
  test = "fisher",
  pValueThreshold = 0.05,
  minCytosinesCount = 10,
  minProportionDifference = 0.1,
  cores=ncores)

print(DMRsNoiseFilterTriangular)

DMRsNoiseFilterTriangularMerged <- mergeDMRsIteratively(DMRsNoiseFilterTriangular,
  minGap = 200,
  respectSigns = TRUE,
  mDataGrp1,
  mDataGrp2,
  minProportionDifference = 0.1,
  pValueThreshold = 0.05,
  test="fisher",
  cores=ncores)

print(DMRsNoiseFilterTriangularMerged)
```

  - `neighbourhood` method, Fisher test
```{r warning=FALSE, message=FALSE, eval=FALSE}
DMRsNeighbourhood <- computeDMRs(mDataGrp1, mDataGrp2,
  method = "neighbourhood",
  test = "fisher",
  pValueThreshold = 0.05,
  minCytosinesCount = 10,
  minProportionDifference = 0.1,
  cores=ncores)

print(DMRsNeighbourhood)

DMRsNeighbourhoodMerged <- mergeDMRsIteratively(DMRsNeighbourhood,
  minGap = 200,
  respectSigns = TRUE,
  mDataGrp1,
  mDataGrp2,
  minProportionDifference = 0.1,
  pValueThreshold = 0.05,
  test="fisher",
  cores=ncores)

print(DMRsNeighbourhoodMerged)
```

  - `bins` method, Fisher test
```{r warning=FALSE, message=FALSE, eval=FALSE}
DMRsBins <- computeDMRs(mDataGrp1, mDataGrp2,
  method = "bins",
  test = "fisher",
  pValueThreshold = 0.05,
  minCytosinesCount = 10,
  minProportionDifference = 0.1,
  cores=ncores)

print(DMRsBins)

DMRsBinsMerged <- mergeDMRsIteratively(DMRsBins,
  minGap = 200,
  respectSigns = TRUE,
  mDataGrp1,
  mDataGrp2,
  minProportionDifference = 0.1,
  pValueThreshold = 0.05,
  test="fisher",
  cores=ncores)

print(DMRsBinsMerged)
```