---
title: "DMRs: BSseq"
author: "Hana Parizkova & Deepak Tanwar"
date: "<b>Created on:</b> 2018-11-25 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  html_document:
    theme: spacelab
    highlight: pyg
    keep_md: no
    number_sections: yes
    fig_width: 8.5
    fig_height: 11
    fig_caption: true
    df_print: paged
    code_folding: show
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
---

# Packages required
```{r, warning=F, message=FALSE}
library(bsseq)
library(DT)
```


# Input files and phenoData

## Negative control
```{r}
pheno.nc <- read.table("./input/anno_neg_control.txt.gz", header = T, sep = "\t", stringsAsFactors = F)

files.nc <- list.files("./input", pattern = "NC_rep", full.names = T)
bs.nc <- read.bismark(
  files = files.nc, sampleNames = pheno.nc$names, strandCollapse = F,
  mc.cores = detectCores() - 1
)

pData(bs.nc) <- pheno.nc
```

## Simulated data
```{r}
pheno.sim <- read.table("./input/anno_sim_data.txt.gz", header = T, sep = "\t", stringsAsFactors = F)

files.sim <- list.files("./input", pattern = "sim_rep", full.names = T)
bs.sim <- read.bismark(
  files = files.sim, sampleNames = pheno.sim$names, strandCollapse = F,
  mc.cores = detectCores() - 1
)

pData(bs.sim) <- pheno.sim
```


# Smoothing
```{r}
bs.smoothed.nc <- BSmooth(BSseq = bs.nc, mc.cores = detectCores() - 1)
bs.smoothed.sim <- BSmooth(BSseq = bs.sim, mc.cores = detectCores() - 1)
```


# Computing t-statistics

```{r}
bs.tstat.nc <- BSmooth.tstat(bs.smoothed.nc,
  mc.cores = detectCores() - 1, estimate.var = "same",
  group1 = pheno.nc$names[pheno.nc$Group == "Group1"],
  group2 = pheno.nc$names[pheno.nc$Group == "Group2"],
  local.correct = TRUE,
  verbose = TRUE
)

bs.tstat.sim <- BSmooth.tstat(bs.smoothed.sim,
  mc.cores = detectCores() - 1, estimate.var = "same",
  group1 = pheno.sim$names[pheno.sim$Group == "Group1"],
  group2 = pheno.sim$names[pheno.sim$Group == "Group2"],
  local.correct = TRUE,
  verbose = TRUE
)
```


## Marginal distribution of the `t-statistic`
```{r, fig.align='center', fig.width=11, fig.height=8.5, fig.cap="Distribution of `t-statistic`."}
par(mfrow = c(1, 2), pty = "s")
plot(bs.tstat.nc)
title("Negative control")

plot(bs.tstat.sim)
title("Simulated data")
```


# DMRs
```{r}
# Negative control
dmr.nc <- dmrFinder(bs.tstat.nc)
# dmr.nc$pValue <- 2 * pt(abs(dmr.nc$areaStat), 4, lower = F)
# dmr.nc$qValue.BH <- p.adjust(p = dmr.nc$pValue, method = "BH")
dmr.nc <- subset(dmr.nc, n >= 10 & abs(meanDiff) >= 0.1)
write.table(dmr.nc,
  file = gzfile("./output/bsseq_dmr_neg_control.txt.gz"), sep = "\t",
  quote = F, row.names = F
)

# Simulated data
dmr.sim <- dmrFinder(bs.tstat.sim)
# dmr.sim$pValue <- 2 * pt(abs(dmr.sim$areaStat), 4, lower = F)
# dmr.sim$qValue.BH <- p.adjust(p = dmr.sim$pValue, method = "BH")
dmr.sim <- subset(dmr.sim, n >= 10 & abs(meanDiff) >= 0.1)
write.table(dmr.sim,
  file = gzfile("./output/bsseq_dmr_simulated_data.txt.gz"), sep = "\t",
  quote = F, row.names = F
)
```

# DMR Tables

## Negative control
```{r}
datatable(
  dmr.nc,
  rownames = F,
  filter = "top", extensions = c("Buttons", "ColReorder"), options = list(
    pageLength = 10,
    buttons = c("copy", "csv", "excel", "pdf", "print"),
    colReorder = list(realtime = FALSE),
    dom = "fltBip"
  )
)
```

## Simulated data
```{r}
datatable(
  dmr.sim,
  rownames = F,
  filter = "top", extensions = c("Buttons", "ColReorder"), options = list(
    pageLength = 10,
    buttons = c("copy", "csv", "excel", "pdf", "print"),
    colReorder = list(realtime = FALSE),
    dom = "fltBip"
  )
)
```


# SessionInfo

```{r}
devtools::session_info()
```