---
title: "DMRs: DMRs plots"
author: "Deepak Tanwar & Hana Parizkova"
date: "<b>Created on:</b> 2018-12-30 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  html_document:
    theme: spacelab
    highlight: pyg
    keep_md: no
    number_sections: yes
    fig_width: 8.5
    fig_height: 11
    fig_caption: true
    df_print: paged
    code_folding: show
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
---

# Packages required
```{r, warning=F, message=FALSE}
library(dmrseq)
```


# BSseq objects

## Negative control
```{r}
load("./input/bsseq_neg_control.RData")
```

## Simulated data
```{r}
load("./input/bsseq_sim_100.RData")
```


# DMR files

## Negative control
```{r}
files.nc <- list.files(path = "./input", pattern = "neg_control.txt", full.names = T)
files.nc <- files.nc[grep(pattern = "anno", x = files.nc, invert = T)]
names(files.nc) <- sapply(files.nc, function(x) strsplit(x, "\\.|/")[[1]][4])

read.nc <- lapply(files.nc, function(x) GRanges(read.delim(x, sep = "\t", stringsAsFactors = F, header = T)))
```


## Simulated data
```{r}
anno.sim <- read.table("./input/anno_sim_data.txt.gz", sep = "\t", header = T, stringsAsFactors = F)
files.sim <- list.files(path = "./input", pattern = "sim_data.txt", full.names = T)
files.sim <- files.sim[grep(pattern = "anno", x = files.sim, invert = T)]

names(files.sim) <- sapply(files.sim, function(x) strsplit(x, "\\.|/")[[1]][4])

read.sim <- lapply(files.sim, function(x) {
  a <- read.delim(x, sep = "\t", stringsAsFactors = F, header = T)
  cols <- colnames(a)

  if (length(cols[grep(pattern = "qval", x = cols)]) == 0) {
    return(GRanges(a))
  } else {
    b <- GRanges(a)
    b <- b[b$qval <= 0.05, ]
    return(b)
  }
})

pData(bs.sim$bs) <- anno.sim
```



# Annotation Human Genome
```{r, message=F, warning=F, eval=F}
anno <- getAnnot("hg19")
```


# Regions plot Simulated data {.tabset .tabset-dropdown}

```{r, results='asis', fig.align='center', fig.height=6, fig.width=7, message=F, warning=F}
## DMRs
dmrs <- data.frame(bs.sim$gr.dmrs, mncov = bs.sim$dmr.mncov, delta = bs.sim$delta)
dmrs <- GRanges(dmrs[order(dmrs$delta, decreasing = T), ])

## Results to be plotted
n1 <- paste(names(read.sim)[2:5], collapse = " | ")
n1 <- gsub(pattern = "_dmr|_sim_data", replacement = "", x = n1)

n2 <- paste(names(read.sim)[6:9], collapse = " | ")
n2 <- gsub(pattern = "_dmr|_sim_data", replacement = "", x = n2)

n3 <- paste(names(read.sim)[c(1, 10:12)], collapse = " | ")
n3 <- gsub(pattern = "_dmr|_sim_data", replacement = "", x = n3)


for (i in 1:100) {
  n <- paste0("Region", i, ": ", "delta ", round(dmrs$delta[i], 3))

  cat("\n \n")
  cat(paste("##", n))
  cat("\n \n")

  plotDMRs(
    BSseq = bs.sim$bs, regions = dmrs[i, ], testCovariate = "Group",
    compareTrack = GenomicRangesList(read.sim[c(2:5)]), qval = F, stat = F,
    highlightMain = F,
    main = n1
  )

  plotDMRs(
    BSseq = bs.sim$bs, regions = dmrs[i, ], testCovariate = "Group",
    compareTrack = GenomicRangesList(read.sim[c(6:9)]), qval = F, stat = F,
    highlightMain = F,
    main = n2
  )

  plotDMRs(
    BSseq = bs.sim$bs, regions = dmrs[i, ], testCovariate = "Group",
    compareTrack = GenomicRangesList(read.sim[c(1, 10:12)]), qval = F, stat = F,
    highlightMain = F,
    main = n3
  )

  cat("\n \n")
}
```



# SessionInfo

```{r}
devtools::session_info()
```