---
title: "Common regions passing MTC"
author: "Deepak Tanwar & Hana Parizkova"
date: "<b>Created on:</b> 2018-12-30 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  html_document:
    theme: spacelab
    highlight: pyg
    keep_md: no
    number_sections: yes
    fig_width: 8.5
    fig_height: 11
    fig_caption: true
    df_print: paged
    code_folding: show
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
---

# Packages required
```{r, warning=F, message=FALSE}
library(GenomicRanges)
library(DT)
library(data.table)
```

# Input files

## Simulated 100 DMRs
```{r}
read.dmr <- GRanges(read.delim("./input/simulated_DMRS.txt.gz", sep = "\t", stringsAsFactors = F, header = T))
```


## DMR files (simulated data)

```{r}
files.sim <- list.files(path = "./input", pattern = "sim_", full.names = T)
names(files.sim) <- sapply(files.sim, function(x) strsplit(x, "\\.|/")[[1]][4])

read.sim <- lapply(files.sim, function(x) GRanges(read.delim(x, sep = "\t", stringsAsFactors = F, header = T)))

# Filtering regions based on FDR
sim.new <- list()

for (i in 1:length(read.sim)) {
  n <- names(read.sim)[i]
  sim.new[[i]] <- read.sim[[i]][read.sim[[i]]$qval <= 0.05]
  names(sim.new)[i] <- n
  colnames(mcols(sim.new[[i]])) <- paste(n, colnames(mcols(sim.new[[i]])), sep = ":")
}
```


# Merge GRanges

## Function
```{r}
meta_GR <- function(gr1, gr2) {
  ranges <- subsetByOverlaps(gr1, gr2, minoverlap = 1)
  revRanges <- subsetByOverlaps(gr2, gr1)
  hits <- findOverlaps(gr1, gr2)

  idx1 <- subjectHits(hits)
  idx2 <- queryHits(hits)

  r1 <- gr1[idx2]

  values <- DataFrame(gr2[idx1])
  colnames(values) <- c("GRanges", colnames(values)[2:ncol(values)])
  mcols(r1) <- c(mcols(r1), values)
  return(r1)
}
```


## Regions common among all different analysis

```{r}
regions.common <- Reduce(function(x, y) {
  meta_GR(gr1 = x, gr2 = y)
}, c(list(read.dmr), sim.new))
```


## Regions common with DMRs for each method

```{r}
regions.common.each <- list()
for (i in 1:length(sim.new)) {
  n <- names(sim.new)[i]
  tmp <- meta_GR(gr1 = read.dmr, gr2 = sim.new[[i]])

  regions.common.each[[i]] <- tmp
  names(regions.common.each)[i] <- n
}
```


# Tables {.tabset .tabset-pills}

## Common regions
```{r}
datatable(
  data.frame(regions.common),
  rownames = F,
  filter = "top", extensions = c("Buttons", "ColReorder"), options = list(
    pageLength = 10,
    buttons = c("copy", "csv", "excel", "pdf", "print"),
    colReorder = list(realtime = FALSE),
    dom = "fltBip"
  )
)
```


## Regions common with DMRs for each method {.tabset .tabset-dropdown}

```{r, echo=FALSE,include = FALSE}
# You need this code to conduct the magic dependences attaching...
DT::datatable(matrix())
```

```{r, results='asis'}
system("mkdir -p ./output/results_mapping_dmrs")

for (i in seq_along(regions.common.each)) {
  name <- names(regions.common.each)[i]
  cat("\n \n")
  cat(paste("###", name))
  cat("\n \n")
  print(htmltools::tagList(DT::datatable(data.frame(regions.common.each[[i]]),
    rownames = F, width = "100%"
  )))
  cat("\n \n")


  write.table(data.frame(regions.common.each[[i]]),
    file = gzfile(paste0("./output/results_mapping_dmrs/", name, ".txt.gz")),
    quote = F, sep = "\t", row.names = F
  )
}
```


# Truth table

## Calculation
```{r}
tab <- data.frame(matrix(nrow = length(sim.new), ncol = 3))
colnames(tab) <- c("Technique", "Regions_identified", "Regions_map_to_DMRs")
rownames(tab) <- names(sim.new)
tab$Technique <- gsub(pattern = "_dmr|_sim_data", replacement = "", x = rownames(tab))

for (i in 1:nrow(tab)) {
  n <- rownames(tab)[i]
  tmp.r <- data.frame(sim.new[[n]], stringsAsFactors = F)
  tmp.c <- regions.common.each[[n]]

  tab$Regions_identified[i] <- nrow(tmp.r)
  tab$Regions_map_to_DMRs[i] <- length(unique(ranges(tmp.c)))
}

write.table(tab, gzfile("./output/truth_table.txt.gz"), quote = F, sep = "\t")
```

## Results
```{r}
datatable(
  data.frame(tab),
  rownames = T,
  filter = "top", extensions = c("Buttons", "ColReorder"), options = list(
    pageLength = 10,
    buttons = c("copy", "csv", "excel", "pdf", "print"),
    colReorder = list(realtime = FALSE),
    dom = "fltBip"
  )
)
```


# SessionInfo

```{r}
devtools::session_info()
```