##############################
## @Author : Deepak Tanwar  ##
## @Date :   20181211       ##
##############################

## Makefile to compile RMarkdown file to HTML.

all: task1
task1:
	Rscript -e 'rmarkdown::render("20181125-filtered_simulated_data_dmrseq.Rmd", "html_document")' 2> log >> log
