---
title: "dmrseq analysis"
author: "Deepak Tanwar"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: spacelab
    highlight: pyg
    keep_md: no
    number_sections: yes
    fig_width: 8.5
    fig_height: 11
    fig_caption: true
    df_print: paged
    code_folding: show
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
  fontsize: 11pt
  geometry: margin=1in
  documentclass: article
  pdf_document:
    fig_caption: yes
    fig_height: 8
    fig_width: 8
    number_sections: yes
    toc: yes
    df_print: kable
    highlight: tango
  word_document: default
editor_options: 
  chunk_output_type: console
---

# Packages required

```{r}
library(dmrseq)
```

# Negative control

## Input files
```{r}
files.neg <- list.files("./input", pattern = "neg", full.names = T)

# files.list.neg <- as.list(files.neg)
names(files.neg) <- as.character(sapply(basename(files.neg), function(x) strsplit(x, "\\.")[[1]][1]))

bismarkBSseq.neg <- read.bismark(
  files = files.neg,
  sampleNames = names(files.neg),
  rmZeroCov = TRUE,
  strandCollapse = FALSE,
  fileType = "cov",
  verbose = TRUE,
  mc.cores = 16
)

grp1.neg <- colnames(bismarkBSseq.neg)[c(1,3,5)]
grp2.neg <- colnames(bismarkBSseq.neg)[c(2,4,6)]

anno.neg <- data.frame(samples = colnames(bismarkBSseq.neg), group = rep(c("group1", "group2"), 3))
rownames(anno.neg) <- anno.neg$samples

pData(bismarkBSseq.neg) <- anno.neg

# required coverage: at least 5 in at least 2 samples in each group
loci.idx.neg <- which(rowSums(getCoverage(bismarkBSseq.neg[, grp1.neg], type = "Cov") >= 5) >= 2 &
  rowSums(getCoverage(bismarkBSseq.neg[, grp2.neg], type = "Cov") >= 5) >= 2)

bs.filtered.neg <- bismarkBSseq.neg[loci.idx.neg, ]


regions.neg <- dmrseq(
    bs = bs.filtered.neg,
    testCovariate = "group",
    BPPARAM = BiocParallel::MulticoreParam(workers = 16)
  )
save(regions.neg, file = "./output/dmrseq_neg.RData", compress = T)
```


## Annotation

```{r}
annoTrack <- getAnnot("hg19")
```

## Regions plot

```{r}
plotDMRs(bismarkBSseq.neg, regions=regions.neg[regions.neg$qval < 0.9,][1:6,],
         testCovariate="group",annoTrack=annoTrack)
```



# Sim data

## Input files
```{r}
files.sim <- list.files("./input", pattern = "sim", full.names = T)

names(files.sim) <- as.character(sapply(basename(files.sim), function(x) strsplit(x, "\\.")[[1]][1]))

bismarkBSseq.sim <- read.bismark(
  files = files.sim,
  sampleNames = names(files.sim),
  rmZeroCov = TRUE,
  strandCollapse = FALSE,
  fileType = "cov",
  verbose = TRUE,
  mc.cores = 16
)

grp1.sim <- colnames(bismarkBSseq.sim)[1:3]
grp2.sim <- colnames(bismarkBSseq.sim)[4:6]

anno.sim <- data.frame(samples = colnames(bismarkBSseq.sim), group = rep(c("group1", "group2"), each = 3))
rownames(anno.sim) <- anno.sim$samples

pData(bismarkBSseq.sim) <- anno.sim

# required coverage: at least 5 in at least 2 samples in each group
loci.idx.sim <- which(rowSums(getCoverage(bismarkBSseq.sim[, grp1.sim], type = "Cov") >= 5) >= 2 &
  rowSums(getCoverage(bismarkBSseq.sim[, grp2.sim], type = "Cov") >= 5) >= 2)

bs.filtered.sim <- bismarkBSseq.sim[loci.idx.sim, ]


regions.sim <- dmrseq(
    bs = bs.filtered.sim,
    testCovariate = "group",
    BPPARAM = BiocParallel::MulticoreParam(workers = 16)
  )

save(regions.sim, file = "./output/dmrseq_sim.RData", compress = T)
```

## Regions plot

```{r}
plotDMRs(bismarkBSseq.sim, regions=regions.sim[regions.sim$qval < 0.9,][1:6,],
         testCovariate="group",annoTrack=annoTrack)
```