##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200214       ##
##############################

## Makefile to compile RMarkdown file to HTML.

all: task1
task1:
	Rscript -e 'rmarkdown::render("defiant.Rmd")' 2> log >> log
