---
title: "bsseq"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

According to https://www.bioconductor.org/packages/devel/bioc/vignettes/bsseq/inst/doc/bsseq_analysis.html.

#### Negative control
- read in data:
```{r warning=FALSE, message=FALSE, eval=FALSE}
library("bsseq")

M <- read.table("../data/data_neg_control.M.gz", header=TRUE, sep="\t", stringsAsFactors = F)
cov <- read.table("../data/data_neg_control.cov.gz", header=TRUE, sep="\t", stringsAsFactors = F)
chr <- M$chr
pos <- M$pos
M$chr <- NULL
M$pos <- NULL
cov$chr <- NULL
cov$pos <- NULL
M <- data.matrix(M)
cov <- data.matrix(cov)
sampleNames <- gsub(".M", "", colnames(M))
colnames(M) <- sampleNames
colnames(cov) <- sampleNames

bs <- BSseq(chr=chr, pos=pos, M=M, Cov = cov, sampleNames=sampleNames)
```
- smoothing:
```{r warning=FALSE, message=FALSE, eval=FALSE}
# bs.smoothed <- BSmooth(bs, verbose=TRUE, mc.cores = 10)
# save(bs.smoothed, file = "analysis.RData", compress = T, compression_level = 9)

load("analysis.RData")
```