##############################
## @Author : Deepak Tanwar  ##
## @Date :   20200213       ##
##############################

## Makefile to compile RMarkdown file to HTML.

all: task1
task1:
	Rscript -e 'rmarkdown::render("20200213-simulated_data_pWGBSSimla.Rmd")' 2> log >> log
