---
title: "DMRs: dmrseq"
author: "Deepak Tanwar & Hana Parizkova"
date: "<b>Created on:</b> 2018-12-19 <br> <b>Updated on:</b> `r Sys.Date()`"
output:
  html_document:
    theme: spacelab
    highlight: pyg
    keep_md: no
    number_sections: yes
    fig_width: 8.5
    fig_height: 11
    fig_caption: true
    df_print: paged
    code_folding: show
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
  fontsize: 12pt
  geometry: margin=1in
  documentclass: article
---

# Packages required

```{r, warning=F, message=F}
library(dmrseq)
library(DT)
```

# Input files
Read in input files and create a `BSseq` object.
# Negative control
```{r}
files.nc <- list.files("./input", pattern = "NC", full.names = T)

anno.nc <- read.table("./input/anno_neg_control.txt.gz", header = T, sep = "\t", stringsAsFactors = F)

bismarkBSseq.nc <- read.bismark(
  files = files.nc,
  sampleNames = anno.nc$names,
  rmZeroCov = TRUE,
  strandCollapse = FALSE,
  fileType = "cov",
  verbose = TRUE,
  mc.cores = 16
)

pData(bismarkBSseq.nc) <- anno.nc
```

## Simulated data
```{r}
files.sim <- list.files("./input", pattern = "sim_r", full.names = T)

anno.sim <- read.table("./input/anno_sim_data.txt.gz", header = T, sep = "\t", stringsAsFactors = F)

bismarkBSseq.sim <- read.bismark(
  files = files.sim,
  sampleNames = anno.sim$names,
  rmZeroCov = TRUE,
  strandCollapse = FALSE,
  fileType = "cov",
  verbose = TRUE,
  mc.cores = 16
)

pData(bismarkBSseq.sim) <- anno.sim
```

# DMRs analysis

## Negative control
```{r}
dmr.nc <- dmrseq(
  bs = bismarkBSseq.nc,
  testCovariate = "Group",
  BPPARAM = BiocParallel::MulticoreParam(workers = 16)
)

dmr.nc <- data.frame(dmr.nc, stringsAsFactors = F)

write.table(dmr.nc, file = gzfile("./output/dmrseq_dmr_neg_control.txt.gz"), sep = "\t", quote = F, row.names = F)
```

## Simulated data
```{r}
dmr.sim <- dmrseq(
  bs = bismarkBSseq.sim,
  testCovariate = "Group",
  BPPARAM = BiocParallel::MulticoreParam(workers = 16)
)

dmr.sim <- data.frame(dmr.sim, stringsAsFactors = F)

write.table(dmr.sim, file = gzfile("./output/dmrseq_dmr_sim_data.txt.gz"), sep = "\t", quote = F, row.names = F)
```


# DMR Tables
Identified DMRs with q-value not higher than 0.05.
## Negative control
```{r}
datatable(
  dmr.nc,
  rownames = F,
  filter = "top", extensions = c("Buttons", "ColReorder"), options = list(
    pageLength = 10,
    buttons = c("copy", "csv", "excel", "pdf", "print"),
    colReorder = list(realtime = FALSE),
    dom = "fltBip"
  )
)
```


## Simulated data

```{r}
c2 <- dmr.sim$qval[dmr.sim$qval <= 0.05]
datatable(
  dmr.sim,
  rownames = F,
  filter = "top", extensions = c("Buttons", "ColReorder"), options = list(
    pageLength = 10,
    buttons = c("copy", "csv", "excel", "pdf", "print"),
    colReorder = list(realtime = FALSE),
    dom = "fltBip"
  )
) %>%
  formatStyle(
    "qval",
    backgroundColor = styleEqual(c2, rep("#66C2A5", length(c2)))
  )
```


# SessionInfo

```{r}
devtools::session_info()
```