##############################
## @Author : Deepak Tanwar  ##
## @Date :   20181219       ##
##############################

## Makefile to compile RMarkdown file to HTML.

all: task1
task1:
	Rscript -e 'rmarkdown::render("methylKit.Rmd", "html_document")' 2> log >> log
