channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - r-base=3.6.2
  - bioconductor-geoquery=2.54.0
  - r-rmarkdown=2.1
  - java-jdk=8.0.112
  - r-xtermstyle=3.0.5
  - pigz=2.3.4
  - r-devtools=2.0.2
  - bioconductor-dmrseq=1.6.0
  - r-data.table=1.12.8
  - r-tidyverse=1.3.0
  - r-dplyr=0.8.3
  - bioconductor-bsseq=1.22.0
