##############################
## @Author : Deepak Tanwar  ##
## @Date :   20181210       ##
##############################

## Makefile to compile RMarkdown file to HTML.

all: task1
task1:
	Rscript -e 'rmarkdown::render("data_download_and_filter.Rmd", "html_document")' 2> log >> log
